// Builds dist/ from the hand-drawn SVGs in icons/.
//
//   dist/svg/<name>.svg   optimized, normalized single icons
//   dist/sprite.svg       every icon as a <symbol id="<name>">
//   dist/icons.json       shared root attributes + inner markup per icon
//   dist/react/           React components (<ArrowLeftIcon />) + types
//   dist/preview.html     visual catalog, opens straight from disk

import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { optimize } from 'svgo';

const root = fileURLToPath(new URL('..', import.meta.url));
const srcDir = join(root, 'icons');
const distDir = join(root, 'dist');

// Every icon must use exactly these root attributes (see GUIDELINES.md).
// The build rewrites the root tag, so the output is identical for all icons.
const ATTRS = {
  viewBox: '0 0 24 24',
  fill: 'none',
  stroke: 'currentColor',
  'stroke-width': '1.5',
  'stroke-linecap': 'square',
  'stroke-linejoin': 'miter',
};

const NAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const ATTR_RE = /([\w:-]+)="([^"]*)"/g;
const ELEMENT_RE = /<(\w+)((?:\s+[\w:-]+="[^"]*")*)\s*\/>/g;

const svgoConfig = {
  multipass: true,
  plugins: ['preset-default', 'removeXMLNS'],
};

const attrString = (attrs) =>
  Object.entries(attrs)
    .map(([k, v]) => `${k}="${v}"`)
    .join(' ');

const parseAttrs = (source) =>
  Object.fromEntries([...source.matchAll(ATTR_RE)].map(([, k, v]) => [k, v]));

const pascalCase = (name) =>
  name.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());

const camelCase = (attr) => attr.replace(/[-:]([a-z])/g, (_, c) => c.toUpperCase());

function readIcon(name, source) {
  if (!NAME_RE.test(name)) {
    throw new Error(`${name}.svg: file names must be lowercase kebab-case in English`);
  }

  // Validate the source root: svgo drops attributes that equal SVG defaults (e.g. miter).
  const rootSource = source.match(/<svg([^>]*)>/)?.[1];
  if (rootSource === undefined) throw new Error(`${name}.svg: could not read the <svg> element`);
  const rootAttrs = parseAttrs(rootSource);
  for (const [key, expected] of Object.entries(ATTRS)) {
    if (rootAttrs[key] !== expected) {
      throw new Error(
        `${name}.svg: expected ${key}="${expected}" on <svg>, found ${
          rootAttrs[key] === undefined ? 'nothing' : `"${rootAttrs[key]}"`
        }`,
      );
    }
  }

  const { data } = optimize(source, svgoConfig);
  const inner = data.match(/^<svg[^>]*>([\s\S]*)<\/svg>$/)?.[1];
  if (inner === undefined) throw new Error(`${name}.svg: svgo output has no <svg> root`);

  // Keep the format flat (self-closing shapes only) so it maps 1:1 to React
  // elements and the sprite. Colors must come from the root's currentColor.
  const nodes = [...inner.matchAll(ELEMENT_RE)].map(([, tag, attrs]) => [tag, parseAttrs(attrs)]);
  if (inner.replace(ELEMENT_RE, '').trim() !== '') {
    throw new Error(`${name}.svg: only flat, self-closing shapes are supported (no groups, text or styles)`);
  }
  if (/#[0-9a-f]{3,8}\b|rgb\(|hsl\(/i.test(inner)) {
    throw new Error(`${name}.svg: hardcoded colors are not allowed, inherit currentColor`);
  }

  return { name, component: `${pascalCase(name)}Icon`, inner, nodes };
}

const svgFile = (icon) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" ${attrString(ATTRS)}>${icon.inner}</svg>\n`;

const spriteFile = (icons) =>
  [
    '<svg xmlns="http://www.w3.org/2000/svg">',
    ...icons.map((icon) => `<symbol id="${icon.name}" ${attrString(ATTRS)}>${icon.inner}</symbol>`),
    '</svg>',
    '',
  ].join('\n');

const jsonFile = (icons) =>
  JSON.stringify(
    { attributes: ATTRS, icons: Object.fromEntries(icons.map((icon) => [icon.name, icon.inner])) },
    null,
    2,
  ) + '\n';

function reactFile(icons) {
  const baseProps = Object.fromEntries(
    Object.entries(ATTRS).map(([k, v]) => [camelCase(k), k === 'stroke-width' ? Number(v) : v]),
  );
  const toNodes = (nodes) =>
    JSON.stringify(
      nodes.map(([tag, attrs]) => [
        tag,
        Object.fromEntries(Object.entries(attrs).map(([k, v]) => [camelCase(k), v])),
      ]),
    );

  return `// Generated by scripts/build.mjs. Do not edit.
import { createElement, forwardRef } from 'react';

const baseProps = ${JSON.stringify(baseProps)};

function createIcon(displayName, nodes) {
  const Icon = forwardRef(function Icon({ size = 24, title, children, ...props }, ref) {
    const labelled = Boolean(title || props['aria-label'] || props['aria-labelledby']);
    return createElement(
      'svg',
      {
        xmlns: 'http://www.w3.org/2000/svg',
        ...baseProps,
        width: size,
        height: size,
        role: labelled ? 'img' : undefined,
        'aria-hidden': labelled ? undefined : true,
        focusable: 'false',
        ref,
        ...props,
      },
      title ? createElement('title', null, title) : null,
      ...nodes.map(([tag, attrs]) => createElement(tag, attrs)),
      children,
    );
  });
  Icon.displayName = displayName;
  return Icon;
}

${icons.map((icon) => `export const ${icon.component} = /*#__PURE__*/ createIcon('${icon.component}', ${toNodes(icon.nodes)});`).join('\n')}
`;
}

const typesFile = (icons) => `// Generated by scripts/build.mjs. Do not edit.
import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from 'react';

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'ref'> {
  /** Width and height. Defaults to 24. */
  size?: number | string;
  /** Accessible name. Without it (or aria-label) the icon is decorative and hidden from screen readers. */
  title?: string;
}

export type Icon = ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>;

${icons.map((icon) => `export declare const ${icon.component}: Icon;`).join('\n')}
`;

async function previewFile(icons) {
  const template = await readFile(join(root, 'scripts', 'preview.html'), 'utf8');
  const data = icons.map(({ name, component, inner }) => ({ name, component, inner }));
  return template
    .replace('/*__ATTRS__*/{}', JSON.stringify(ATTRS))
    .replace('/*__ICONS__*/[]', JSON.stringify(data));
}

const files = (await readdir(srcDir)).filter((file) => file.endsWith('.svg')).sort();
const icons = await Promise.all(
  files.map(async (file) => readIcon(file.slice(0, -4), await readFile(join(srcDir, file), 'utf8'))),
);

await rm(distDir, { recursive: true, force: true });
await mkdir(join(distDir, 'svg'), { recursive: true });
await mkdir(join(distDir, 'react'), { recursive: true });

await Promise.all([
  ...icons.map((icon) => writeFile(join(distDir, 'svg', `${icon.name}.svg`), svgFile(icon))),
  writeFile(join(distDir, 'sprite.svg'), spriteFile(icons)),
  writeFile(join(distDir, 'icons.json'), jsonFile(icons)),
  writeFile(join(distDir, 'react', 'index.js'), reactFile(icons)),
  writeFile(join(distDir, 'react', 'index.d.ts'), typesFile(icons)),
  writeFile(join(distDir, 'preview.html'), await previewFile(icons)),
]);

console.log(`Built ${icons.length} icons into dist/`);
